### ISSUE TITLE
Deploy não funciona

### ISSUE THREAD

**Issue by MarlonTereziano** [azevgabriel/jogos_educacionais#27]
Ao testar o aplicativo, notei que o deploy para testar os jogos em produção não está funcionando, segue a mensagem de erro, obrigado!
<img width="736" alt="image" src="https://github.com/azevgabriel/jogos_educacionais/assets/80834228/14193825-a600-41bf-a998-5e9a81e0082b">

**Comment by azevgabriel** [comment]
[aprenda-brincando.vercel.app](https://aprenda-brincando.vercel.app/)
